### ISSUE TITLE
Dealing with unseen nodes

### ISSUE THREAD

**Issue by subpath** [VHRanger/graph2vec#3]
Hi! Thanks for your library!

I'm using it to vectorize network graph - graph of IPs communicated with each other. What do you think might be an approach when dealing with new previously unseen IPs (nodes)?
It seems like there are no other options than retrain n2v model from scratch.

In my case skipping them is not an option, and I don't see how I can use tricks from NLP like using synonymous to the unseen word.

I would be grateful for any thoughts or suggestions. 

Cheers, 
Alex

**Comment by VHRanger** [comment]
Hey,

Sorry about the late response, I somehow didn't get notifications for this project...

What I would suggest is taking the average of the neighboring nodes' embeddings.

So if you have a new Node, presumably you know its edges, pointing to its neighbors. Then take the embeddings of all the neighbors and apply some normalization over it (average, weighed average, or sum if you did an L2 norm on your embeddings).

This can predict the location of the new node before re-training
